### ISSUE TITLE
With two sessions when we play then pause on one, then refresh the other, it goes to the next track

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#70]
We need to check why and fix this.
Maybe currentTrack is lost in the nature in temporal

Reproduce the bug:
1. Start one session create a room on it then hit play button.
2. Start another session, it should be synced to the previous one, but here is the bug, current track is not synced with the first session. It appears to be the next track from the waiting list and also the room is not playing but the song looks to be paused, it shouldn't

**Comment by Devessier** [comment]
The issue seems to be due to the initial track timer being launched with an empty duration. It results in the initial track being automatically skipped.

We should take care of setting the context timer duration for the initial track.

<img width="1605" alt="CleanShot 2021-07-16 at 17 57 18@2x" src="https://user-images.githubusercontent.com/29370468/125975620-536e73bb-1b8e-4aee-bb5a-7d4518897fa7.png">
