### ISSUE TITLE
Sync two parallel sessions on createRoom

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#71]
Start two sessions.
Create room from one, the other one should display the created room too

Solution:
Bring down to low level the CREATE_ROOM_CALLBACK listener in the state machine to force the transition even if the specific state machine is not the CREATE_ROOM emitter

**Comment by Devessier** [comment]
The issue seems to be due to the initial track timer being launched with an empty duration. It results in the initial track being automatically skipped.

<img width="1605" alt="CleanShot 2021-07-16 at 17 57 18@2x" src="https://user-images.githubusercontent.com/29370468/125975620-536e73bb-1b8e-4aee-bb5a-7d4518897fa7.png">

**Comment by prastoin** [comment]
@Devessier I think you're talking about [this issue](https://github.com/AdonisEnProvence/MusicRoom/issues/70) isn't it ?

**Comment by Devessier** [comment]
Indeed. I marked my comment as outdated.
